services:
    app.shipping_calculator.demo_pickup:
        class: Magentix\SyliusPickupDemoPlugin\Shipping\Calculator\PickupDemoCalculator
        public: true
        tags:
            - { name: sylius.shipping_calculator, calculator: demo_pickup, form_type: Magentix\SyliusPickupDemoPlugin\Form\Type\Shipping\Calculator\PickupDemoConfigurationType, label: "Demo Pickup" }
